Proposta de solução para o exercício 01_02
VideojogosLusofona/lp2_exercicios pull request #105
Opened 2020-10-28 16:09 UTC by FRP7

Qualquer tipo de feedback é bem vindo!

2020-11-02 10:54 UTC, fakenmc requested changes
Olá Francisco,

Ainda não olhei para o código, mas a nível de funcionalidade tens os seguintes problemas:

* Não se diz altura/largura da matriz, mas sim número de linhas/número de colunas.
* Número de casas também não é o mais correto, mas sim número de elementos.
* Sem nada em contrário deves assumir que as matrizes e vectores trabalham com números reais e não apenas com inteiros.
* Quando são pedidos os números a inserir na matriz, o utilizador não faz ideia onde o número vai ser inserido (em que linha, em que coluna). Esta informação devia aparecer.
* Experimentei com uma matriz 2x3 e estranhamente o programa pediu-me um vector de "2 casas". Ora neste caso devia ter-me pedido um vector 3x1 para o poder multiplicar pela matriz.

2020-11-02 20:49 UTC, FRP7 commented
Olá professor, segui o seu feedback e coloquei também o programa a verificar se o utilizador está a colocar o input certo.

2020-11-11 22:25 UTC, fakenmc requested changes
* O programa tem dois _warnings_ que têm de ser corrigidos.
* Porque razão o programa não aceita zeros na matriz?
* Experimentei inserir uma matriz 3x2, que só pode ser multiplicada por um vetor 2x1. No entanto o programa pediu-me um vetor 3x1.
* Antes de submeteres a próxima versão confirma que os resultados do programa estão correctos aqui: https://matrix.reshish.com/multiplication.php

2020-11-12 15:42 UTC, FRP7 commented
Olá professor, segui o seu feedback.

2020-11-14 17:46 UTC, fakenmc requested changes
* O programa está agora a dar resultados corretos.
* Propriedades começam com maiúscula....
* Usar _camelCase_. Por exemplo `inputmatrixlines` é incorreto. Deveria ser `inputMatrixLines`.
* A indentação está esquisita em algumas partes do código. Usa a formatação automática de código do VS Code ou do VS 2019.
* Porque razão fazes quebras de linha quando as linhas não vão ultrapassar os 80 carateres (por exemplo nos `TryParses()`)?
* Um vector é na realidade uma matriz. Parte do código de `ConstructVector()` é quase igual a `ConstructMatrix()`. Não vou exigir esta alteração para aceitar o exercício, mas podes pensar nisso se quiseres. A mesma coisa para `PrintMatrix()` e `PrintVector()`.

2020-11-14 21:44 UTC, FRP7 commented
Olá professor, segui o seu feedback.
Quanto aos vetores e matrizes, não vem de momento ideias novas de como tornar o código de construção e exposição melhor mas, se eventualmente surgir alguma ideia nova faço pull request.

2020-11-14 22:26 UTC, fakenmc requested changes
* Algumas propriedades ainda começam com minúscula... 
* Testa o código antes de resubmeteres para verificar que está tudo OK.

2020-11-15 19:27 UTC, FRP7 commented
Olá professor, já corrigi os nomes das propriedades e corrigi um bug que descobri com os testes que permitia ao user escolher zero ou um número negativo quando define o número de linhas e colunas.
Acho que já está okay, não assisti a mais problemas com os testes.

2020-11-15 19:47 UTC, merged

2020-11-15 19:47 UTC, fakenmc commented
Solução aceite.