Proposta de solução para o exercício 01_09
VideojogosLusofona/lp2_exercicios pull request #106
Opened 2020-10-29 12:47 UTC by FRP7

Qualquer tipo de feedback é bem vindo!

2020-11-02 11:36 UTC, fakenmc requested changes
Olá Francisco, aqui vai o _feedback_:

* Não se dizer altura/comprimento do _array_, mas sim nº de linhas e nº de colunas.
* A variável do tipo `Checker` deve ser declarada no início do bloco onde é usada e não no meio.
* Além disso repara que não estás a criar uma nova instância de `Checker` pois em nenhum momento fazes `new`. Apenas estás a declarar a variável (e como disse no comentário anterior, num sítio pouco aconselhado).
* O método `Check()` não pode ser `static`. Tal como indicado no enunciado, deve ser um método de instância. No entanto para invocares este método tens primeiro de criar uma instância de `Checker`, coisa que não estás a fazer como referi no ponto anterior.

Depois de corrigires estes problemas verifico o resto.

2020-11-02 22:43 UTC, FRP7 commented
Olá professor, segui o seu feedback e também resolvi um bug que só descobri agora e o programa já verifica se os inputs estão corretos e mostra onde estão a ser colocados os valores nos elementos.

2020-11-11 22:31 UTC, fakenmc requested changes
* Porque razão as variáveis da classe `Checker` são `static` se vamos querer usar uma instância da classe e não a classe diretamente?
* Porque razão existem `WriteLines` no construtor? O construtor serve para inicializar as variáveis/propriedades de instância, caso necessário.
* Há aqui uma grande confusão entre classes e instâncias. O código não faz sentido. Lê melhor o enunciado. Se tiveres dúvidas no enunciado, pergunta.

2020-11-12 17:56 UTC, FRP7 commented
Olá professor, segui o seu feedback e revi o enunciado e o código todo.

2020-11-14 17:52 UTC, fakenmc requested changes
Se os construtores apenas servem para inicializar um objecto, porque razão chamas o método `Check()` no construtor? Há alguma coisa a inicializar na classe `Checker`? É mesmo preciso este construtor fazer alguma coisa?

2020-11-14 21:52 UTC, FRP7 commented
Olá professor, segui o seu feedback.

2020-11-14 22:28 UTC, fakenmc requested changes
* Se o construtor não faz nada, porque razão lá está?
* Testa o programa bem antes de resubmeteres. Usa diferentes _inputs_ para verificar se o código está mesmo a detetar as linhas horizontais, verticais e diagonais com 4 ou mais elementos do elemento especificado.

2020-11-15 19:39 UTC, FRP7 commented
Olá professor, já retirei o construtor e corrigi uma série de bugs que descobri com os testes:
- O _user_ não podia colocar `float `na matriz
- O _user_ podia escolher zero ou um número negativo quando definia o número de linhas e colunas da matriz
- Dependendo do número de linhas e colunas, alguns `for` que fiz para verificar as linhas não funcionavam.
- A análise das linhas ignorava os números que apareciam no meio ou seja, se tivesse _1 2 1 1 1_ e pedisse para verificar o _1_, iria assumir que estão 4 em linha.

De resto acho que já está tudo bem.

2020-11-15 19:51 UTC, fakenmc commented
Francisco, lê o enunciado de novo. Qual é o tipo que é suposto ser colocado na matriz? É `float`?

2020-11-15 22:19 UTC, fakenmc commented
Não está ainda a funcionar bem, como podes ver neste caso:

```
Qual é o valor que quer procurar?
1
1 3 4 5 6 

1 4 5 3 4 

1 4 5 3 6 

1 3 5 6 3 

4 5 2 4 5 

6 3 3 -1 1 


Não existe linha
```

2020-11-16 12:07 UTC, FRP7 commented
Olá professor, fiz as seguintes melhorias:

- corri o bug que o prof mostrou
- corrigi um bug que impedia de o _user_ colocar o valor zero nos elementos.
- retirei código morto

Tenho uma dúvida: quando verifico as linhas diagonais, basta só verificar uma de cada lado ou tem que ser mesmo todas? 

1 2 3
4 5 6
7 8 9

Se tiver esta matriz, o código como está agora deteta as seguintes linhas: "1 5 9" e "3 5 7". Tenho que detetar também a "4 8", a "2 6" e a "6 8"? 
Desculpe se não estou a expressar bem 😅

2020-11-18 16:04 UTC, fakenmc commented
Continua a não funcionar:

```
Qual é o valor que quer procurar?
0
6 8 5 7 0 

6 7 8 0 8 

5 4 0 -1 9999 

1 0 55 4 3 

2 5 6 7 8 

4 2 4 5 6 


Não existe linha
```

Como referi antes, testa bem todas as possibilidades antes de submeteres a próxima correção.

2022-10-09 18:58 UTC, closed without merging