Proposta de solução do exercício 01_15
VideojogosLusofona/lp2_exercicios pull request #108
Opened 2020-10-30 12:07 UTC by FRP7

Qualquer tipo de feedback é bem vindo!

2020-11-02 12:28 UTC, fakenmc requested changes
* A `struct` que apresentas é mutável, pois é possível mudar os seus valores, mesmo que apenas dentro da própria `struct`.
* Se a `struct` representa **um** intervalo de tempo porque razão tens propriedades para **seis** intervalos de tempo? Revê a aula onde são dadas propriedades, há um exemplo parecido.
* Não é pedido qualquer método `InsertTime()` no enunciado, muito menos um que inicialize o intervalo de tempo aleatoriamente. A única forma de definires os valores internos de um tipo imutável é no seu construtor.
* No programa de teste porque razão precisas de uma variável de classe? E porque razão a instancias naquele local?
* Na resposta 1 estás a confundir imutabilidade com encapsulação.

2020-11-04 12:30 UTC, FRP7 commented
Olá professor, segui o seu feedback. 
Desta vez já não mostra os commits todos 😅

2020-11-11 22:40 UTC, fakenmc requested changes
A resposta à segunda questão está incorreta. Vê nos slides o que é a sintaxe de **inicialização de objetos com propriedades**.

2020-11-14 17:48 UTC, fakenmc requested changes
Resposta correta. Italiciza as palavras em inglês (e.g. _bug_), remove a linha em branco na lista Markdown e coloca _keywords_ de código com formatação de código (e.g. `struct`) e a solução será aceite.

2020-11-14 23:03 UTC, FRP7 commented
Olá professor, fiz as formatações que pediu. 
Amanhã vou rever com mais calma os outros exercícios que deu feedback.

2020-11-14 23:08 UTC, fakenmc requested changes
* Atenção ao limite de 80 carateres por linha.
* Continuas a ter uma linha em branco na lista Markdown (entre as respostas 1 e 2).

Isto não é uma corrida a ver quem faz mais exercícios. É preferível que faças os exercícios com calma, que testes no Visual Studio o código que apresentas (sempre que isso seja possível) e que tenhas a certeza que respondeste bem às questões e ao _feedback_. Neste momento tens quase 20 exercícios pendentes. Não comeces novos até teres esses resolvidos e entendidos. O teu esforço é importante mas tens que ter mais atenção aos detalhes.

2020-11-15 19:53 UTC, merged

2020-11-15 19:53 UTC, fakenmc commented
Solução aceite.