Proposta de solução do exercício 01_22
VideojogosLusofona/lp2_exercicios pull request #110
Opened 2020-10-31 12:05 UTC by FRP7

Qualquer tipo de feedback é bem vindo!

2020-11-02 12:44 UTC, fakenmc requested changes
* Porque razão as enumerações estão a ser criadas dentro de `Sword` se vão ser usadas fora dela?
* Os elementos das propriedades devem começar com maiúscula.
* Porque razão ocultas o `name` e `description` da classe base? Mudou alguma coisa no seu intuito ao nível da classe `Sword`?
* Variáveis começam com maiúscula. Se o enunciado pede campos começados com minúscula o mais provável é não estar a referir-se a propriedades (e.g. `length`).
* Repara bem no _camel case_ das variáveis e tipos no enunciado. A ideia é fazeres o mesmo no teu código.
* Porque razão inicias `description` e `name` no construtor de `Sword` se isso já está a ser feito pelo construtor de `GameItem` através de `base(name, description)` que tu corretametne colocaste à frente do construtor de `Sword`? Ainda por cima `description` está a ser inicializado duas vezes.
* Porque razão existem `WriteLines()` no construtor? Se o construtor serve para construir qual é o sentido de estar a mostrar informação ao utilizador?
* Na pergunta 3 basta uma linha de código... e não precisas de mencionar os tipos pelo nome, embora possas. Só faz sentido fazer isso quando existem muitos parâmetros opcionais e só queres referir alguns.
* A reposta 4 podia estar mais clara e atenção ao limite de 80 carateres.
* Uma classe `abstract` não é vazia e pode ter métodos, propriedades, corpo... atenção à formatação de _keywords_ (`abstract` sim, abstract não).

2020-11-04 11:31 UTC, FRP7 commented
Olá professor, já segui o seu feedback mas fiz push e infelizmente mostra os outros commits mas eu acho que já percebi agora qual é o problema.
Eu primeiro fiz rebase do meu commit mas depois fiz pull antes de alterar e fazer push, acho que foi o pull que causou isso.

2020-11-11 22:36 UTC, fakenmc commented
Mesmo problema. Vou fechar este _pull request_ pois contém _commits_ de colegas teus e altera 4 ficheiros (só deve ser resolvido um exercício por _pull request_).

2020-12-09 18:02 UTC, FRP7 commented
Olá professor, acho que se esqueceu de fechar o _pull request_.

2020-12-09 18:02 UTC, fakenmc commented
Indeed

2020-12-09 18:02 UTC, closed without merging