Proposta de solução do exercício 01_14
VideojogosLusofona/lp2_exercicios pull request #113
Opened 2020-10-31 18:19 UTC by FRP7

Qualquer tipo de feedback é bem vindo!

2020-11-02 16:05 UTC, fakenmc requested changes
* Pergunta 1: 
  * Atenção à formatação de código quando referes _keywords_ de código.
  * Atenção à pontuação, vírgulas, etc.
* Pergunta 2:
  * Porque razão usas o verbo "obter"? Estás a obter alguma coisa?
  * Atenção à pontuação, vírgulas, etc.
* Pergunta 3: Errado, tens duas que não são auto-implementadas.
* Pergunta 4: Correta.
* Pergunta 5: Deves dar a assinatura completa do construtor (assinatura, não a declaração; vê os slides de LP1 para veres a diferença).
* Pergunta 6: mesma situação, deves dar a assinatura completa do método.
* Pergunta 7: Muito incompleto e nos únicos locais onde realmente colocaste essa documentação, está incorrecto. Vê os slides de LP1 para veres como o Visual Studio te pode ajudar a fazer isto de forma quase automática.
* Pergunta 8: Era pedido um método `static` que recebe um iterável e imprime os seus conteúdos de forma formatada, não um método `Main()` que cria esse iterável. Podes até criar o método `Main()` para tu próprio testares o tal método `static`, mas não o acrescentas à tua resposta.

2020-11-04 15:14 UTC, FRP7 commented
Olá professor, já segui o seu feedback.

2020-11-14 16:26 UTC, fakenmc requested changes
* Atenção ao número de linhas em branco entre as perguntas. Listas em Markdown não devem ter linhas em branco a separar cada item.
* Pergunta 1:
  - Atenção ao limite de 80 carateres por linha.
  - Falta um vírgula entre "valor" e "aliás".
* Pergunta 2:
  - As variáveis de instância são neste caso tipos de valor, pelo que não faz muito sentido falares em "referência".
  - É apenas pedido o seu propósito, não a zona de memória onde estão localizadas.
* Pergunta 7:
  - Dizes que tudo é uma variável, mesmo no caso das propriedades (o que está errado neste último caso - sobretudo porque não existe tal coisa como "variável auto implementada"). No entanto não é importante dizeres que é uma variável ou propriedade. Basta dizeres qual o seu propósito. Por exemplo, em vez de dizeres "Variável do número de jogos jogados." dizes "Número de jogos jogados.". O mesmo se pode dizer nos comentários do método.
  - Tens umas linhas apenas com uns "//" avulsos. Remove-as.
* Pergunta 8:
  - Problemas de indentação na primeira linha.
  - Deste o nome `Map()` a este método. Achas que esse nome reflete o que o método faz?
  - Este tipo de métodos `static` são geralmente métodos utilitários a serem usados pelo restante código. Será que faz sentido serem `private`?
  - O método não funciona como pretendido. Num teste que fiz, eis o _output_:
```
Name              Filename      Sucess Rate    Top Score
--------------------------------------------------------
Lala              lala.txt       39.2%   947729.000
L3l3              l3l3.txt       31.7%   114552.836
ABDCLele          abcdlele.txt       31.5%    36100.801
Li                li.txt       31.2%    22877.334
TESTELolo         testelolo.txt       29.5%    41031.602
LolaXPTOZZZ       lolaxptozzz.txt       31.6%    98969.219
Lula              lula.txt       40.1%    86214.781
```

2020-11-14 22:41 UTC, FRP7 commented
Olá professor, segui o seu feedback

2020-11-14 22:50 UTC, fakenmc requested changes
* Pergunta 1:
  - Leste bem o que escreveste? "que na qual é um tipo de valor"?
  - `int` e `float` não são variáveis.
* Pergunta 7:
  - O parâmetro `won` "verifica" alguma coisa?
* Pergunta 8:
  - Continua mal indentada a primeira linha.
  - Achas que `DrawMap()` é um bom nome para o método? Estás a desenhar um mapa?
  - Com _tabs_ não vais lá. Tens de testar o código antes de submeter senão estás a perder o teu tempo e o meu.

2020-11-16 20:04 UTC, FRP7 commented
Olá professor.
Acho que já resolvi o problema da impressão dos resultados, já é possível colocar resultados com uma `string `maior sem afectar os outros elementos (a não ser que seja demasiado grande).
Também segui o resto do feedback (a primeira linha já está melhor indentada na pergunta 8?).

2020-11-18 16:17 UTC, fakenmc requested changes
* Pergunta 1: `struct` perdeu a formatação de código...
* Vários sítios: sucesso em inglês é "success" e não "sucess". Porque razão alteraste algo que estava bem?
* Pergunta 7:
  * O que significa "Gameswon"? 
  * Sê consistente. Se colocas pontos finais em alguns locais, coloca em todos.
  * No último método, o `bool` indica se ganhou "um" jogo, ou aquele jogo ("o" jogo)? Antes tinhas bem, novamente mudaste para pior.
* Pergunta 8:
  * Primeira linha mal indentada (`/// <summary>`).
  * Ponto final no comentário do parâmetro.
  * O resultado impresso está melhor, mas ainda não está como pedido no enunciado. Repara bem no alinhamento dos números.

2022-10-09 18:59 UTC, closed without merging