Proposta de solução do exercício 02_06
VideojogosLusofona/lp2_exercicios pull request #122
Opened 2020-11-11 14:57 UTC by FRP7

Qualquer tipo de feedback é bem vindo!

2020-11-14 17:06 UTC, fakenmc requested changes
* `Random.Range()` não devolve `ints`.

2020-12-12 22:35 UTC, fakenmc requested changes
* Não podes estar sempre a fazer _force push_, depois não consigo ver as alterações que fizeste. O uso de _force pushes_ no Git é considerado má prática e deve ser deixado apenas para situações de último caso, irresolúveis de outra forma.
* Definir um intervalo de tempo com `int`s parece-me limitativo.
* Estar sempre a criar uma instância  de `Random` cada vez que a co-rotina é invocada parece-me muito má ideia.

2020-12-13 15:11 UTC, FRP7 commented
Olá professor, segui o seu feedback e fiz umas alterações ao código.

2020-12-13 17:42 UTC, fakenmc commented
A solução está praticamente correta, mas há duas coisas que podem ficar melhor:

* Já que apresentas a classe toda, os valores do intervalo podiam ter sido dados como variáveis do editor. Colocares números específicos no meio do código é má prática.
* Na co-rotina será necessário a variável `value` estar definida para todo o método? Não podes reduzir o seu _scope_?

2022-10-09 18:58 UTC, closed without merging