Proposta de solução do exercício 02_12
VideojogosLusofona/lp2_exercicios pull request #124
Opened 2020-11-11 18:40 UTC by FRP7

Qualquer tipo de feedback é bem vindo!

2020-11-14 17:23 UTC, fakenmc requested changes
* A matéria para resolução deste exercício será dada na próxima aula (já coloquei os slides). Volto a dizer que acho melhor fazeres e compreenderes os exercícios mais simples antes de passares para estes.
* De resto:
  - Ultrapassas várias vezes os 80 carateres por linha.
  - Não faz sentido herdares de uma classe e uma interface quando a classe já implementa essa interface.
  - Não podes alterar código existente.

2020-12-09 17:58 UTC, FRP7 commented
Olá professor, refiz o exercício com mais calma.
Qualquer tipo de feedback ou ideias são bem vindas.

2020-12-12 19:51 UTC, fakenmc requested changes
* Quando fazes `Reload()` não fará sentido adicionar 10 ao stamina (e não simplesmente mete-lo a 10)? Esse valor 10 deve ser uma constante ou algo semelhante e não colocado ali de qualquer maneira.
* A propriedade `IsAlternate` nunca é alterada no código. Ou seja, quando um adaptador deste estilo é criado, os ataques serão sempre horizontais ou verticais.
* Haverá necessidade da enumeração `MeleeAttacks` e da variável `meleeAttacks`? A propriedade `IsAlternate` não representa exatamente a mesma coisa? Princípio mais importante de todos: [KISS](https://en.wikipedia.org/wiki/KISS_principle).

2020-12-12 19:52 UTC, fakenmc commented
E outra coisa, tens ali um `WriteLine()` a fazer o quê? A ideia é isto funcionar na consola, no Unity e em qualquer _game engine_ que possa aparecer no futuro.

2022-10-09 18:57 UTC, closed without merging