Proposta de resolução ao Ex1
VideojogosLusofona/lp2_exercicios pull request #15
Opened 2019-10-15 09:13 UTC by xShadoWalkeR

2019-10-16 07:11 UTC, nunofachada requested changes
Várias coisas:

* Ocorreu um problema com a codificação do ficheiro, como podes ver [aqui](https://github.com/VideojogosLusofona/lp2_exercicios/pull/15/files). Tens de gravar os ficheiros em UTF-8. Usa o Visual Studio Code para editares as respostas, pois este usa UTF-8 por omissão.
* Teres uma variável pública não-_read-only_ na classe `Program` é má prática. Existem muitas soluções alternativas, talvez a mais simples seja instanciares `Calculo` no `Main()`, passando-lhe o _array_ de valores, e depois passares essa instância de `Calculo` como parâmetro do construtor de `Display` (desta forma `Display` nunca tem acesso ao _array_, nem tinha que ter). Outra razão para fazeres isto é que normalmente esse tipo de dados `static` são de evitar, pois são equivalentes a variáveis globais.
* O uso de LINQ na parte da moda está mal indentado.

De resto boa solução.

2019-10-17 10:38 UTC, nunofachada requested changes
- Continua a aparecer desformatado, como podes ver [aqui](https://github.com/VideojogosLusofona/lp2_exercicios/pull/15/files).
- A variável `calculo` na classe `Display` ter ser explicitamente privada. Atenção que o comentário que lá está, está errado, pois estás a declarar a variável `calculo` (ou seja, a dizer que ela existe), e não a instanciá-la. Criar uma nova instância requer `new`.
- A classe `Calculo` aparece duas vezes, e a classe `Program` desapareceu.

2019-10-18 08:52 UTC, fakenmc commented
Olá Leandro, o código está perfeito, a codificação ainda não, como podes ver [aqui](https://github.com/VideojogosLusofona/lp2_exercicios/pull/15/files).

2019-10-18 09:35 UTC, fakenmc commented
Olá Leandro, o código não está a compilar, tem dois erros.
Além disso, foi entretanto aceite outra solução (bastante diferente da tua), por isso era fixe conseguires fazer _rebase_ do teu ramo no ramo `upstream/master` e colocar a tua solução como solução 2.

2019-10-18 10:56 UTC, xShadoWalkeR commented
isto estava só a dar problemas no rebase mas acho que ficou bem. Tinha esses 2 erros porque estava a fazer código no bloco de notas e não reparei que tinha de iniciar calc antes do display.

2019-10-18 11:12 UTC, fakenmc commented
Leandro, o _rebase_ não ficou muito bem. Para não lixar o repositório vou fechar este _pull request_. Submete um _pull request_ novo, com um ramo baseado no `upstream/master` mais recente, com a tua solução adicionada em cima da do João.

2019-10-18 11:12 UTC, closed without merging