Ex41
VideojogosLusofona/lp2_exercicios pull request #22
Opened 2019-10-15 11:54 UTC by RodrigoPrinheiro

Bom dia professor

Estou a ter problemas com este exercício, não estou a conseguir fazer o método `GetScores()` . O meu `HighScoreManager` funciona à base de um array com 10 posições e estava a usar o método `Array.Sort()` mas este método faz o sort através do `Item1` dos tuplos.
É então suposto abordar o problema através de um `IEnumerable<T>` para guarar a *score board* ou á alguma forma de chegar à solução com o que tenho.

2019-10-17 10:57 UTC, fakenmc commented
O método `Sort()` da classe `Array` tem vários _overloads_, alguns dos quais permitem que uses uma classe comparadora externa que implementa `IComparer`. Desta forma podes usar o critério de ordenação que te for mais conveniente e não critério por omissão.

2019-10-18 23:20 UTC, RodrigoPrinheiro commented
Acho que o exercício agora encontra-se correto, mas gostava de evoluir a tabela no método `ToString()` que considero um pouco simples de momento, se poder dar algumas indicações de como a melhorar agradeço.

2019-10-19 18:09 UTC, nunofachada requested changes
* Classe `HighscoreManager`:
  * Variável de instância `_comparer` deve ser privada.
  * No método `Save()` não precisas daquela chamada a `Flush()`. O objetivo desse método é outro, vamos falar nisso numa das próximas aulas.
  * No primeiro método `AddScore()` estás a declarar variáveis no meio do método (devem ser declaradas no início). Não chames essas variáveis de "suporte", pois pode causar confusão com as variáveis de suporte das propriedades. Além disso a lógica deste método está desnecessariamente complexa, acho que o podes simplificar.
  * O segundo método `AddScore()` não me parece necessário, e mesmo que fosse não faz sentido ter um código tão semelhante ao anterior. Ou eliminas este segundo método ou este simplesmente chama o primeiro. No entanto acho que o podias eliminar, pois o código cliente (que utiliza instâncias de `HighscoreManager`) não tem que estar a instanciar tuplos.
  * No método `ToString()` estás a declarar variáveis no meio do código. Além disso estás a assumir que tens 10 scores e podes ter menos. Ou arranjas uma outra variável para contar o número de _scores_ colocados no _array_ ou usas uma lista pré-alocada com 10 posições (`new List<...>(10)`), que já te oferece essa funcionalidade sem ser menos eficiente do que um _array_.
* Classe `CompareTuples`:
  * Se a diferença entre _scores_ for 0.3, qual vai ser o resultado de `Convert.ToInt32()` nesta diferença? Acho que não é isso que pretendes.
* Classe `Program`:
  * Deves fazer mais testes, nomeadamente tentar usar um ficheiro pré-existente, testes com menos _scores_, etc, etc.

2019-10-21 09:36 UTC, nunofachada requested changes
Rodrigo, apesar do programa funcionar (a maior parte das vezes), continua com alguns problemas, sendo o maior é que está demasiadamente complicado (não-KISS). Alguns comentários:

* Classe `HighscoreManager`:
  * No construtor vais sempre instanciar `_scores` da mesma forma, seja qual for o resultado do `if`, por isso podes fazê-la antes do `if`. Não te preocupes com a "ineficiência" no caso de teres a excepção. Se houver excepção o programa termina e a memória é libertada, não há qualquer ineficiência prática em instanciares um _array_ de 10 posições e depois o programa terminar logo a seguir.
  * No método `Save()` estás a tentar gravar 10 _scores_ mesmo quando não os tens. Como referi no _feedback_ anterior, o tamanho fixo do _array_ (10) é diferente do número de _scores_ que lá tens. Volto a dizer, isto seria muito mais simples (KISS) e igualmente eficiente se usasses uma lista de _scores_ pré-alocada com 10 posições, e não um _array_. É que nesse caso o `Count` da lista dá-te o número de _scores_ (e não o número de posições pré-alocadas na lista).
  * O método `AddScore()` ficava com metade do tamanho e muito menos dado a _bugs_ se usasses uma lista. Estes potenciais _bugs_ podem ainda ser vistos na quantidade de vezes que tens de testar se o conteúdo de dada posição do _array_ é `null`, como por exemplo no método `ScoreLine()`. Este tipo de programação é de evitar pois é dada a _bugs_.
* Classe `CompareTuples`:
  * Continuas com o mesmo _bug_. Não é por multiplicares por 1000 que o resolves.
* Classe `Program`:
  * Seria útil se também percorresses `hsMng2`, para ver se está tudo OK.

2019-10-24 10:42 UTC, nunofachada requested changes
* Geralmente é bom organizarmos o código em métodos, mas criar muitos métodos e métodozinhos pode ser contra-producente e complicar o código. Por exemplo, o construtor de `HighscoreManager()` (e lembra-te que os construtores devem ser tão simples e curtos quanto possível), invoca o método `ReadFile()`, que por sua vez invoca `GetPlayerScore()` (que só tem duas linhas de código), que por sua vez invoca `AddScore()`. Isto torna o código difícil de seguir e é mais ineficiente (estamos a meter e a tirar métodos da _stack_ e a saltar entre pontos de execução do código). Pelo menos o `GetPlayerScore()` devia ir à vida, pois nem sequer é usado em mais lado nenhum. Mesmo o `ReadFile()` não me chocava se passasses a sua lógica para o construtor, mas senão quiseres fazê-lo não há problema. 
* No método `AddScore()`, quando usas o método `Remove()` para remover algo de uma lista, a lista vai ter de procurar, índice a índice, onde está o elemento a remover. É bastante ineficiente. Se sabes qual é o índice do item a remover é muito mais eficiente usares o método [`RemoveAt()`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.removeat), pois não tem de fazer procuras.
* Por último, num dos testes podias tentar inserir mais de 10 _scores_ de modo a verificares que os _scores_ mais baixos saltam fora.

2019-10-26 17:27 UTC, merged

2019-10-26 17:27 UTC, fakenmc commented
Obrigado Rodrigo, solução aceite.