Corrigir perguntas 1 e 3 do ex18 de 01
VideojogosLusofona/lp2_exercicios pull request #24
Opened 2019-10-15 12:45 UTC by PmaiWoW

Alterações/Correções pedidas no exercício 18.

2019-10-15 13:01 UTC, nunofachada requested changes
* Pergunta 1: se `w2` for `null` então a instância atual vai aparecer depois de `null`. Será que isso faz sentido, ou faria mais sentido meter os `nulls` todos para o fim?
* Pergunta 3: existe o mesmo problema que no caso anterior, e ainda o facto de não estares a verificar se ambas são `null`.
* Em ambas as perguntas: qual é o resultado de `Convert.ToInt32(0.23f)` por exemplo? Será que é isso que pretendes?

2019-10-15 13:55 UTC, PmaiWoW commented
Tenho uma dúvida quanto a instâncias `null` na comparação.
Testei o código e tentei fazer com que essas instâncias ficassem todas no final da lista, mas isto não acontecesse quando chamo o método `Sort()` da lista.

2019-10-17 15:51 UTC, nunofachada requested changes
* Na pergunta 1: ou metes `else` em todos os `if` a partir do segundo, ou não metes em nenhum. Acho que ficava melhor não meteres em nenhum.
* Na pergunta 3 continuas a não verificar se **ambas** são `null` (o mais fácil era até verificares logo se ambas são a mesma referência, já sabias que eram iguais e que devias retornar zero). Neste momento se ambas forem `null` vais devolver -1, quando na realidade querias devolver 0 (igualdade). Além disso continuas a ter o tal `else` no fim sem necessidade.

2019-11-14 16:11 UTC, nunofachada requested changes
* Porque razão usas `ReferenceEquals()` na alínea 3? Um simples `==` não funciona para verificar igualdade de referências em tipos de referência?
* Fica mais simples fazer _debug_ senão meteres `\n` no _output_ de `ToString()` (aliás, é má prática fazê-lo, pois a ideia do `ToString()` é dar um resumo curto de uma linha sobre o objeto em questão).
* Ao corrigir esta tua resposta aprendi uma coisa nova. Em comparações com `null` o resultado tem de ser sempre "qualquer objeto é maior que `null`". Ou seja, na alínea 3 está correto, mas na alínea 1 não. Experimenta meter uns `null`s na lista de `Weapon`s e logo percebes porquê.

2019-11-15 10:09 UTC, nunofachada requested changes
* A instrução `if (this == null) ...` é equivalente a dizeres em voz alta "Se eu não existir, então...". Ou seja, não faz sentido, pois `this` nunca vai ser `null` (tu estás a falar, logo existes).
* Mete literalmente uns `null`s na lista de `Weapons` para testares se está a funcionar bem. Os `null`s devem sempre aparecer primeiro nas ordenações.

2019-11-15 14:20 UTC, merged

2019-11-15 14:20 UTC, fakenmc commented
Olá Pedro, solução aceite.