Proposta de resolução do exercício 31
VideojogosLusofona/lp2_exercicios pull request #25
Opened 2019-10-15 13:51 UTC by ThomasFranque

2019-10-17 15:34 UTC, nunofachada requested changes
Olá Tomás,

* Copiaste mal o enunciado. Tens de copiar diretamente o Markdown, senão perdes a formatação e o limite de 80 carateres, como foi o caso. Por acaso o enunciado até tinha um problema (referia nome do `Loot` em vez de descrição, por isso aproveitas e ao copiares o Markdown isso fica também corrigido.
* Responde a cada questão separadamente, na sua alínea.
* Na classe `Loot`, coloca um espaço antes do operador lambda.
* Na resposta 3:
  - Por alguma razão estás a usar modo de citação Markdown (linhas começadas com >). Isso não é necessário.
  - Fica mais correto dizeres "uma **instância de uma** `struct` é igual a ~uma~ outra se (...)"

2019-10-18 23:58 UTC, ThomasFranque commented
Olá, em conjunto com as mudanças pedidas, adicionei algum código simples em HTML no ficheiro _markdown_ para auxiliar a leitura. Ao fazê-lo, recebi o erro `no-inline-html`. Pergunto se o que fiz não é uma boa prática e se devo remover.

2019-10-19 00:04 UTC, ThomasFranque commented on solucoes/01/31.md
> +1. <a name="ex1"></a>
HTML nos 3 Tópicos

2019-10-19 18:18 UTC, nunofachada requested changes
* Falta linha em branco entre "## Pergunta" e "31 - Considera...".
* É considerado má prática ter HTML no meio do Markdown, mas como infelizmente Markdown nativo não suporta _links_ internos, não vejo outra forma de fazeres o que pretendes. Não lhe chames é "Exercício 1", etc, mas sim "Questão 1", etc, senão fica confuso, parece que te estás a referir a outros problemas.
* Estás com alguns problemas de indentação nos blocos de código. Corrige por favor.
* Na questão 2 é pedido explicitamente para colocares _loot_ num conjunto (_set_), algo que não estás  a fazer.
* Na questão 3 atenção ao máximo de 80 carateres por linha.

2019-10-21 09:40 UTC, merged

2019-10-21 09:40 UTC, fakenmc commented
Obrigado Tomás, solução aceite.