Add solution to exercise 7 on the folder 01
VideojogosLusofona/lp2_exercicios pull request #33
Opened 2019-10-21 17:58 UTC by Freeze88

Solução para o exercício 7 dos exercícios de revisão de LP1.

2019-10-21 18:11 UTC, nunofachada requested changes
Olá André, são necessárias algumas melhorias:

* Copia todo o enunciado (não copiaste a pergunta). Copia diretamente do código-fonte Markdown, não do texto HTML que é mostrado no _browser_.
* Limita o número de carateres por linha a 80. Nota que uma nova linha em Markdown não corresponde a um parágrafo, por isso podes carregar no ENTER sempre que a linha estiver a ficar muito longa. Para iniciares um novo parágrafo é necessário uma linha em branco no Markdown.
* A formatação de código é \`assim\` (fica `assim`) e não 'assim' (que simplesmente fica 'assim'). Deves também colocar em formatação de código o nome dos métodos, como por exemplo `Main()` e `GCD()`.
* Quando mostrares o que é impresso na consola podes usar um bloco de texto não formatado simples, como por exemplo (usas `text` em vez de `cs`):

\`\`\`text
Isto é impresso na consola
\`\`\`

cujo resultado vai ser

```text
Isto é impresso na consola
```

* Apesar da resposta estar correta, podia estar mais clara. Podias por exemplo indicar qual é a técnica de programação que está a ser usada (quando um método se chama a si próprio), e ser mais claro na resposta à questão, nomeadamente em que consiste a operação do método `GCD()`  - algo que não é suposto ser impresso no ecrã, mas sim respondido por ti na resposta.

2019-10-21 20:37 UTC, Freeze88 commented
Modificação ao exercício 7 dos exercícios de revisão de LP1, refiz um pouco o que tinha, não sei como explicar de outra forma mais clara ou completa.

2019-10-21 21:09 UTC, nunofachada requested changes
Olá André, ficou muito melhor, só faltam alguns detalhes:

* Quando dizes "argumentos de fora", referes-te a que argumentos exatamente?
* Verifica com um corretor ortográfico, tens 2 ou 3 palavras mal escritas.
* Coloca uma linha em branco antes do bloco de texto não formatado (é boa prática).

2019-10-24 11:26 UTC, merged

2019-10-24 11:27 UTC, fakenmc commented
André, aceitei o _pull request_, fiz apenas duas pequenas melhorias para teres em conta nas próximas submissões:

* As palavras inglesas devem ser colocadas em itálico, ou seja, deve aparecer _array_ e não array.
* Faltava um espaço entre duas palavras.