tentativa solução 1
VideojogosLusofona/lp2_exercicios pull request #36
Opened 2019-10-26 23:06 UTC by FPTheFluffyPawed

Aqui vai o primeiro exercício feito de LP2, espero que esteja bem!

2019-10-27 12:02 UTC, nunofachada requested changes
Inácio, a primeira resposta está essencialmente correta, mas são necessárias algumas melhorias no Português:

* "basta ~só assinalar com~ **referir** o nome ~correto~ **completo, incluindo o _namespace_**".
* "Se ~queríamos~ **quiséssemos** o `Random` ~de *dotnet*~ **do .NET**,
usaríamos ~com~ `System.Random`, e se ~queríamos~ **quiséssemos** o `Random` de Unity, usaríamos `UnityEngine.Random`.

Sobre a segunda resposta, o Unity também te deixa ter controlo sobre a sequência de números pseudo-aleatórios a produzir (usando o método [`InitState()`](https://docs.unity3d.com/ScriptReference/Random.InitState.html)). A segunda parte da resposta está certíssima, só falta dizeres a "palavra-chave" (que uma das classes é, e outra não é). Nesta segunda resposta também tens alguns erros de Português, que deves corrigir. Por exemplo, "certidão" não tem o significado que pensas, como podes ver [aqui](https://dicionario.priberam.org/certid%C3%A3o).

2019-10-27 12:45 UTC, FPTheFluffyPawed commented
Hm, então será que deveria remover a primeira parte da segunda resposta? A segunda parte foi escrita para ajudar o meu ponto na primeira parte, mas não sei como reescrever a primeira parte, sem parecer que me estou a repetir. Elimino a primeira parte, ou tento reescrever? Adicionalmente, a palavra-chave tem que haver com o *randomness* das classes?

2019-10-27 12:55 UTC, fakenmc commented
Relativamente à 2ª resposta:

* A primeira parte está incorreta, pois podes definir a sequência de números aleatórios no Unity, com o tal método que referi. Logo se está incorreta, removes.
* A segunda parte está correta apenas a parte em que dizes que no Unity a "instância" existente é única, e no caso do .NET podes ter diferentes e independentes instâncias (ou seja, no Unity só podes ter uma sequência de números pseudo-aleatórios, e no .NET podes ter várias e independentes umas das outras). Qual é a particularidade (_keyword_, palavra-chave) da classe do Unity que lhe permite fazer isso (ou mais especificamente, dos seus métodos e propriedades)? Que característica é essa e que não está presente no caso dos métodos e propriedades do `Random` do .NET?

2019-10-27 16:06 UTC, FPTheFluffyPawed commented
Estive a procurar e a investigar, será o *keyword* a palavra *stream*, sendo que Unity utiliza um *stream* único para gerar os valores ao calhas, enquanto o .NET utiliza *streams* únicos?

2019-10-27 16:43 UTC, fakenmc commented
Olá Inácio, não tem nada a ver com o Unity, tem a ver com a matéria de C# dada em LP1. Quando os métodos são chamados ao nível da classe e não de instâncias específicas, esses métodos são... ?

2019-10-27 17:52 UTC, FPTheFluffyPawed commented
Esses métodos são invocados, certo? Quer dizer, que na classe do Unity, permita-nos invocar os métodos diretamente?

2019-10-27 18:31 UTC, fakenmc commented
Inácio, tens de rever a matéria, isto é daquelas coisas básicas. Aula 7 de LP1.

2019-10-27 19:02 UTC, FPTheFluffyPawed commented
Ah, os métodos são *static*, era isso? Desculpe, não estava a fazer a conexão no meu cérebro!

2019-10-27 19:03 UTC, fakenmc commented
Isso ;)

2019-10-27 19:04 UTC, FPTheFluffyPawed commented
Aaah. Okay, vou fazer *commit* então! Não acredito que me estava a esquecer disso...

2019-10-27 22:07 UTC, nunofachada requested changes
Inácio,

1. Na primeira resposta não aplicaste todas as correções sugeridas. Por favor revê o que eu pedi e reescreve a resposta em conformidade.
2. Na segunda resposta, como já tinha referido, a primeira parte não estava correta. Tanto no Unity como no .NET (e não _dotnet_) podes ter especificar uma _seed_ e ter sequências de valores pseudo-aleatórios ([calhas](https://www.efapel.pt/pt/produtos/calhas-tecnicas) são outras coisas) reproduzíveis. Ambas as abordagens servem esse propósito. Além disso nada disso é perguntado na questão. A questão pergunta as diferenças ao nível da **instanciação** e **invocação dos métodos** que produzem números pseudo-aleatórios. Sobre isso só começaste a falar no fim da tua resposta, nomeadamente a questão do `static`. É sobre isso que tens de falar.

Sugiro também que:

* Uses um corretor ortográfico de modo a que a tua solução seja aceite mais rapidamente.
* Releias duas vezes e devagar aquilo que escreveste antes de fazeres _commit_.

2019-10-27 22:18 UTC, FPTheFluffyPawed commented
O meu corretor ortográfico não parece apanhar regras de gramática, infelizmente. Então para a segunda resposta, se eu dizer que a diferença entre o Unity e .NET é que os métodos de Unity são `static` enquanto os de .NET não são `static`, a resposta está correta?

2019-10-27 22:26 UTC, fakenmc commented
* Não são só regras de gramática. Faltam-te vários acentos, por exemplo. Se usares o VS Code, tens pré-visualizador de Markdown, corretor de Português, etc...
* A resposta 2 correta é nesse sentido sim. Não basta é dizeres só isso, tens de elaborar um pouco mais, bastando para isso responderes exatamente ao que é perguntado. Lê bem a pergunta e responde aos dois pontos:
  1. Qual é a diferença ao nível da **instanciação** das respetivas classes.
  2. Qual é a diferença ao nível da **invocação** dos respetivos métodos.
* Ambos os pontos estão diretamente relacionados com o facto da classe `Random` do Unity ser `static`.
* Sugiro também que futuramente faças mais exercícios de código, pois valem mais e é o que sai mais nos testes. Além disso, minimizas a questão do Português.

2019-10-27 22:40 UTC, FPTheFluffyPawed commented
Hmm, então poderia dizer que como os métodos de Unity são `static`, nós não podemos instanciar o `Random` para um objeto, tendo que diretamente chamar os métodos (ex: `Random.Range`), enquanto para o `Random` de .NET, nós temos que instanciar uma váriavel `Random` para poder utilizar os métodos.

Na parte da invocação, seria algo próximo ao o que disse? Desculpe se estou a fazer perguntas tontas, é que tenho problemas a perceber a metodologia de programação, enquanto sou um pouco melhor a programar, se isso faz sentido.

2019-10-27 22:42 UTC, fakenmc commented
Sim, a resposta é essencialmente essa. Atenção aos termos usados e ao Português.

2019-10-27 23:17 UTC, nunofachada requested changes
Estás mais perto, alguns reparos:

* "os ~metódos~ **métodos da classe `Random` do** ~de~ Unity são ~por preferência,~ `static`"
* "enquanto os métodos **da classe `Random`** do .NET"
* Invocar um método é a mesma coisa que chamar um método. Os métodos da classe `Random` do Unity podem perfeitamente ser invocados/chamados, ao contrário do que afirmas. Se não pudessem ser invocados/chamados, não serviam para nada. São é invocados diretamente na classe, e não num objeto/instância.
* "pois ~que~ estes métodos são `static` ~por definição~,"
* Na última dizes que é preciso "instanciar a classe como um objeto primeiro", e isso é verdade, mas falta clarificar que os métodos do .NET são depois invocados nesse objeto/instância criado.

2019-10-28 11:11 UTC, merged

2019-10-28 11:12 UTC, fakenmc commented
Obrigado Inácio, solução aceite. Nas próximas submissões aposta mais nos exercícios de código.