Proposta de solução, 02, 0017
VideojogosLusofona/lp2_exercicios pull request #47
Opened 2019-11-19 18:18 UTC by JBernardoRebelo

Algumas dúvidas sobre o IDisposable, daí não estar corretamente implementado.

2019-11-19 18:21 UTC, fakenmc commented
Dou-te _feedback_ na quinta, hoje já não consigo.

2019-11-19 18:26 UTC, JBernardoRebelo commented
Sem problema professor

2019-11-21 19:08 UTC, nunofachada requested changes
João, são necessárias algumas alterações:

* O nome do ficheiro solução é `017.md` e não `0017.md`. O engano foi meu, mas entretanto já corrigi, corrige também (o mais fácil é fazeres _rebase_ ou _merge_ em `origin/master`).
* Vê melhor a documentação do `IObservable<T>`. Esta interface define o método `Subscribe()` para que sejam registados observadores, e a forma dos observadores cancelarem o registo é através do objeto devolvido por esse mesmo método. Esse objeto implementa `IDisposable`, logo a forma de cancelar o registo de observador é... vê na documentação. Resumindo, não são necessário os métodos `registerObserver()` e `removeObserver()`, pois isso derrota o propósito destas interfaces. É sim necessária a implementação do método `Subscribe()`, bem como de uma classe que implemente `IDisposable` que cancele o registo (é geralmente uma classe privada interna do sujeito observável, vê na documentação).
* A ideia do _observer pattern_ é que os observadores e os sujeitos não conheçam os tipos uns dos outros. Logo, o tipo genérico `T` destas interfaces é suposto ser a informação enviada pelos sujeitos aos observadores usando uma abordagem _push_. Ou seja, neste caso os sujeitos enviam teclas aos observadores.
* Ficava mais claro se a classe `ObserverGen` se chamasse `AbstractObserver`. O nome atual dá ideia que é um observador genérico, o que não é verdade, pois já estás a assumir um tipo específico `T`.
* A ideia do método `OnCompleted()` é, segundo a documentação, uma notificação aos observadores indicando que o sujeito parou de enviar dados, de modo a que os observadores cancelem o registo. Repara, neste caso é responsabilidade dos observadores, e não do sujeito, de cancelar o registo. Sempre que o método `OnCompleted()` seja chamado, o respetivo observador devem cancelar o registo, invocando o método `Dispose()` no tal objeto devolvido no método `Subscribe()`... vê a documentação e os exemplos na API do .NET.
* Os _patterns_ são ideias gerais e não específicas, ou seja, podes ver _n_ formas diferentes de implementar cada _pattern_, como é o caso destas interfaces nativas do C# (uma forma do _observer pattern_), dos eventos nativos do C# (outra forma do _observer pattern_) ou dos `UnityEvent` (ainda outra forma diferente do  _observer pattern_). No fundo fazem todos a mesma coisa, mas de formas diferentes.

2019-11-22 11:51 UTC, nunofachada requested changes
* João, como referi na última explicação, o parâmetro genérico destas interfaces deve ser a informação que o sujeito passa aos observadores (a tecla). Esta é uma abordagem _push_, logo o sujeito envia diretamente a informação (tecla) quando invoca os respetivos métodos `OnNext()`.
* Creio que a classe interna `Unsubscriber` tem acesso à lista de observadores de `Subject` (mesmo sendo esta privada), não sendo necessário `Unsubscriber` ter uma referência interna para essa lista.
* Não me parece fazer muito sentido a classe `AbstractObserver` implementar duas vezes a mesma interface com parâmetros genéricos diferentes. Vê o primeiro ponto.

2019-11-22 16:41 UTC, fakenmc commented
João, tens dois ficheiros, remove por favor o que está incorreto.

2019-11-22 18:07 UTC, nunofachada requested changes
* A classe `Subject` não deveria implementar `IObservable<T>`?
* Uma vez que se trata de uma abordagem _push_, a classe `Subject` não tem que disponibilizar publicamente a última tecla lida, pois a mesma é enviada diretamente aos observadores.
* Na classe `AbstractObserver` tens um método `Unsubscribe()` com 4 linhas de código (2 na realidade), que só é chamado uma vez dentro de `OnCompleted()`, que por sua vez só tem duas linhas de código (uma delas a chamar o `Unsubscribe()`). Não seria preferível colocar o código do `Unsubscribe()` dentro do `OnCompleted()`?
* Ficava bem se, nos cabeçalhos antes de cada classe, metesses o nome da classe em formatação de código.

2019-11-23 15:19 UTC, JBernardoRebelo commented
Ao implementar IObservable<T> na classe subject fiquei com um erro de casting que só consegui "resolver" se implementasse IObserver<AbstractObserver> na classe AstractObserver, isto não me parece correto e não estou a ver como poderia fazer de uma melhor maneira

2019-11-23 15:25 UTC, fakenmc commented
Olá João, os erros de casting que estás a ter são normais. Estás a fazer um pouco de confusão e tens de olhar melhor para o exercício, bem como para todo o _feedback_ que já te dei, pois não há mais nada que possa dizer, à parte de te resolver o exercício.

2019-11-23 15:26 UTC, fakenmc commented
Os erros de casting são normais, dada a confusão que estás a fazer e devido ao facto de não teres seguido algum do meu feedback.

2020-10-15 10:12 UTC, closed without merging