added solution to exercise 32
VideojogosLusofona/lp2_exercicios pull request #51
Opened 2019-11-21 18:20 UTC by Freeze88

2019-11-21 19:36 UTC, nunofachada requested changes
Olá André, são necessárias algumas alterações:

* Separa cada resposta na sua alínea respetiva, tendo em conta que nas alienas 1 e 2 a resposta é **uma** linha de código.
* A alínea 1 pede apenas para **declarar** uma lista, não para inicializá-la.
* Como indicado na alínea 2, a variável `monst` é do tipo `Monster` e não `Monster?`. Digo isto, pois tens o código errado nesse aspeto. No entanto também é dito na pergunta que a variável já existe, pelo que tecnicamente não vai afetar a tua resposta final à aliena 2.
* A alínea 3 está incorreta, pois o teu método não devolve nada e imprime algo no ecrã, quando não é isso que está a ser pedido.

2019-11-21 21:01 UTC, Freeze88 commented
Peço desculpa, para esclarecer. Não é necessário enviar o código inteiro apenas o que pede? e sobre a alínea 3. O código está completamente incorrecto ou é apenas por não devolver?

2019-11-21 21:25 UTC, fakenmc commented
Olá André, lê bem as perguntas, bem como a minha explicação. Penso que se leres as coisas com calma, é bastante claro.

Nos testes tens de ter a mesma atenção, e responder **exatamente** ao que é pedido, nem mais, nem menos.

2019-11-21 21:28 UTC, fakenmc commented
E desculpa eu por esta resposta, mas penso que é bastante importante que entendas a importância de ler as perguntas com muita calma e muita atenção. Não fazeres uma interpretação correta das perguntas é 99% do caminho para te enganares nas respostas.

2019-11-21 21:31 UTC, Freeze88 commented
Não precisa de pedir desculpa, tem toda a razão. Apenas com a pressa e por vezes medo não faço como deve de ser.

2019-11-21 21:45 UTC, nunofachada requested changes
Muito melhor. Faltam apenas alguns detalhes:

* Na pergunta 1, é pedido apenas para **declarares** a lista, não para a **instanciar** ou **inicializar** sem elementos. Falta ainda o ponto e vírgula no final.
* Na pergunta 3, mais especificamente no Lambda dentro de `Count()`, deves verificar se cada elemento da lista tem valor (`HasValue`), e não se a lista em si (`monsterList`) tem valor.
* Pequeno detalhe: é boa prática uma linha em branco antes de cada bloco de código.

2019-11-22 11:03 UTC, merged

2019-11-22 11:03 UTC, fakenmc commented
Olá André, solução aceite.