Adicionar solução ao exercício 31 de 02
VideojogosLusofona/lp2_exercicios pull request #52
Opened 2019-11-22 13:02 UTC by PmaiWoW

2019-11-22 13:11 UTC, nunofachada requested changes
Na resposta 2, pode ocorrer a exceção que referes em várias situações, mas só referes uma (que por acaso não está bem explicada, pois se o índice levar a um `null`, nunca chegas a ir à propriedade `Bag`). Explica cada situação em que pode acontecer a `NullReferenceException`.

Apesar de eu não pedir explicitamente, a resposta ficava melhor se explicasses porque razão está a ser violado o _dependency inversion principle_.

2019-11-22 16:46 UTC, nunofachada requested changes
Melhor, e por acaso os possíveis `NullReferenceException` são geralmente uma consequência do _dependency inversion principle_. No entanto corrigiste esse problema dos `nulls`, mas o código continua a violar o princípio. O que quero dizer com isto é que acabaste por não explicar corretamente porque razão o código viola o principio. Lembra-te do exemplo do termómetro da aula onde falámos disso.

2019-11-25 11:00 UTC, nunofachada requested changes
A dependência é de classes/tipos e não de objetos. Refere quais são essas classes concretas das quais o código depende, e que podiam estar mais abstraídas (e já agora sugere um tipo mais abstrato alternativo).

2019-11-25 11:57 UTC, PmaiWoW commented
Bom dia stor, 
Com o feedback anterior referece a abstrair classes como Item e NPC, certo? 
Por exemplo em vez de depender de um NPC em concreto, depender de um Agent e em vez de um Item concreto depender de algo como uma interface IItem?
Ou há algo que me está a escapar?

2019-11-25 12:01 UTC, fakenmc commented
Tens razão Pedro, fiz confusão com o exercício. No entanto neste caso não podes abstrair diretamente, ou seja, não podes usar `Agent` mais abstrato vez de `NPC` mais concreto por exemplo. A forma de resolver o problema seria a forma como resolvemos o problema do termómetro na aula.

2019-11-25 12:04 UTC, fakenmc commented
E outra coisa, apesar do _dependency inversion principle_ estar a ser violado também, existe outro princípio que está a ser mais violado. É um princípio que diz que devemos evitar demasiadas dependências entre classes. Vê o tal exemplo do termómetro da aula 6.

2019-11-25 12:05 UTC, fakenmc commented
Esse princípio não é diretamente um dos SOLID, é uma consequência/corolário dos princípio SOLID, nomeadamente do _Open/Closed_ e e do _Dependency inversion_.

2019-11-25 13:59 UTC, fakenmc commented
Obrigado Pedro, solução aceite.

2019-11-25 13:59 UTC, merged