tentativa solução 1
VideojogosLusofona/lp2_exercicios pull request #53
Opened 2019-11-23 13:15 UTC by FPTheFluffyPawed

Olá professor,

Aqui têm a solução, não tenho muita a certeza sobre esta que ainda estou na dúvida sobre o _pattern_, mesmo depois de ter visto os _slides_. Bem, o professor também disse que é para fazer tudo na mesma classe, mas achei estranho, então tentei fazer com duas classes, pelo menos. Enfim, preferia que dê _feedback_ sobre esta solução!

2019-11-23 15:15 UTC, nunofachada requested changes
Olá Inácio, está bom, mas podes fazer as seguintes melhorias:

* O _pattern_ em si está implementado na classe `ReadInput.cs`, por isso sugiro que apresentes apenas essa classe como resposta direta à primeira parte da pergunta. Apresenta o código completo da classe, e não apenas o método `GetVector2()` (e mesmo este método podia ter um nome mais clarificador, tipo `GetMovement()` ou `GetInput()` ou algo do género).
* A segunda parte da pergunta pede também para criares uma _scene_ para testar a _facade_. O código que apresentas da classe `ShowText` é parte da resposta, mas está incompleto, pois pede-se a _scene_ completa, para eu e os teus colegas podermos abrir e testar no Unity. Sugiro que sigas as instruções indicadas na [nota 3](https://github.com/VideojogosLusofona/lp2_exercicios/blob/master/problemas/02.md) sobre como incluir um projeto completo na resposta.

2019-11-23 16:08 UTC, FPTheFluffyPawed commented
Ok, eu trato disso. Como deveria meter a _scene_ na resposta? Meto um ficheiro a parte só com a _scene_ ou com o projeto inteiro de Unity?

2019-11-23 16:09 UTC, fakenmc commented
Colocas o projeto inteiro, de modo a que eu e os teus colegas o possamos abrir e experimentar.
Segue as instruções na nota 3.

2019-11-23 16:30 UTC, FPTheFluffyPawed commented
Penso que fiz bem, pode verificar?

2019-11-23 16:57 UTC, nunofachada requested changes
Olá Inácio, parece estar bem feito (não abri ainda), mas a classe `ReadInput` deixou de ser `static`, sendo agora necessário inclui-la como componente dos _game objects_ que a querem utilizar. Penso que ficaria mais simples para o utilizador desta _facade_ (e mais de acordo com a própria lógica da classe `Input` do Unity), a classe e o método serem `static`, de modo a serem utilizáveis por qualquer _game object_, sem necessidade de incluir como componente.

2019-11-23 18:57 UTC, FPTheFluffyPawed commented
Ok, desta deve ser!

2019-11-23 21:34 UTC, nunofachada requested changes
Olá Inácio, ainda não é desta, mas está quase. Melhorias a fazer:

* Na solução que apresentas (em Markdown, no ficheiro `013.md`), apresentas duas classes sem qualquer contexto. Tens de explicar o que estás a mostrar. A classe de maior interesse (a _facade_) é a classe `ReadInput`, sendo essa que deves mostrar primeiro.
* É boa prática colocares uma linha em branco antes dos blocos de código que apresentas (entre o nome do ficheiro e o código respetivo).
* No fim da tua explicação e de apresentares as duas classes, deves dizer que um projeto Unity com a solução está disponível no link tal e tal, e quem clicar nesse link vai parar à pasta onde colocaste o projeto.
* O teu projeto Unity tem um pequeno _bug_, se conseguires corrigir era bom. Se ficares a pressionar nas teclas para baixo e para a esquerda ao mesmo tempo, a imagem fica assim:
![bug](https://user-images.githubusercontent.com/3018963/69485555-fcc5cb80-0e38-11ea-8150-9a0212ce57ba.png)

2019-11-23 22:06 UTC, FPTheFluffyPawed commented
Ok. Uma pergunta, como é que faço um _link_ a uma pasta em _Markdown_?

2019-11-23 23:51 UTC, nunofachada requested changes
Olá Inácio, está quase. O que falta:

* O Português das tuas explicações não é o melhor. Relê o mesmo com calma e tenta simplificar e melhorar as frases. Pede ajuda a um colega ou outra pessoa se tiver de ser.
* O _link_ para o projeto está incorreto. Uma dica: já estás na pasta `02`, pelo que não precisas de a indicar no _link_...
* Apesar de na resposta a classe `ReadInput` estar a cumprir o limite das 80 colunas, o mesmo não acontece com essa classe no código do projeto. Corrige este pequeno detalhe por favor.

2019-11-24 10:14 UTC, nunofachada requested changes
O _link_ está correto agora e o Português está bastante melhor, apenas alguns reparos para aceitar a resposta:

* O que é um "sub-método"? Nunca falámos disso nas aulas.
* Na palavra "principal" usa aspas em vez de plicas. Em Português falado diz-se "entre aspas", e não "entre plicas".
* _Game object_ não é código, é um termo em Inglês, devendo estar em itálico. Se queres referir-te à classe `GameObject`, então essa não tem um espaço entre as duas palavras.
* "da **nossa** *scene* para mostrar o **nosso** resultado" - É tudo **nosso**? Se calhar podia não ser tudo **nosso**.

2019-11-24 11:15 UTC, nunofachada requested changes
Quase, pois ainda fazes referência a um "sub-método" na explicação da classe `ShowText`.

Outra coisa, nas mensagens de _commit_ é suposto escreveres ou descreveres as alterações que fizeste. Não é suposto dizeres "Tentativa solução 1, 2, 3, 4... etc". Nos próximos _commits_, neste e noutros exercícios, por favor tem esse cuidado.

2019-11-24 11:17 UTC, FPTheFluffyPawed commented
Ah, okay. Eu pensava que desta forma era melhor para poder ver a quantas tentativas vou com as soluções...

2019-11-24 11:18 UTC, merged

2019-11-24 11:19 UTC, fakenmc commented
Obrigado Inácio, solução aceite.