Adicionar solução para o exercício 26 de 02
VideojogosLusofona/lp2_exercicios pull request #56
Opened 2019-11-25 22:13 UTC by PmaiWoW

2019-11-25 23:08 UTC, nunofachada requested changes
Pedro, acho que foste um bocado longe demais. A pergunta pede para simplificar o código, não para o complicar. Não era pedido para alterares a estrutura do código desta forma.
Como guia, pensa no seguinte: só faz sentido usares operadores Lambda em métodos ou propriedades mas quais seja possível obter o respetivo valor numa única linha de código. Se o método/propriedade não devolver nada (caso dos métodos `void` e do `set` das propriedades), não faz sentido na minha opinião estares a usar Lambdas.

2019-11-25 23:40 UTC, PmaiWoW commented
Este problema encontra-se em todos os ficheiros ou apenas na classe Gun?
Pergunto porque estou a ter alguns problemas em como simplificar o código da mesma.

2019-11-26 00:02 UTC, PmaiWoW commented
Coloquei a class Gun da forma mais simples anterior, apenas omitindo as chavetas do ciclo for, mas a minha dúvida anterior mantém-se.

2019-11-26 09:28 UTC, nunofachada requested changes
* O enunciado diz "usando lambdas e eventualmente operadores ternários", ou seja, não precisas de inventar mais simplificações.
* Não percebo porque razão `Weapon` deixou de ter uma propriedade e passou a ter uma variável de instância.
* Como eu disse no meu comentário, não fica muito bonito na minha opinião usares lambdas em métodos que devolvem `void` e em `set` de propriedades, pois a ideia do lambda é aquilo devolver qualquer coisa de forma compacta. Senão devolver nada, fica esquisito, mas é apenas a minha opinião. Vou aceitar esta parte como está, mas futuramente escusas de fazer essa "simplificação" em métodos `void` e no `set` das propriedades.

2019-12-03 17:05 UTC, fakenmc commented
Olá Pedro, solução aceite.

2019-12-03 17:05 UTC, merged