Adicionar solução ao exercício 27 de 02
VideojogosLusofona/lp2_exercicios pull request #57
Opened 2019-11-25 22:39 UTC by PmaiWoW

2019-11-25 23:09 UTC, nunofachada requested changes
Mesmo problema que o exercício anterior.

2019-11-26 00:09 UTC, PmaiWoW commented
Da mesma forma que corrigi o exercício 26, fi-lo, também, para este exercício no último _commit_.

2019-11-26 09:30 UTC, nunofachada requested changes
Continua muito complicado e com "simplificações" a mais. Lê o meu comentário no outro problema e aplica neste.

2019-12-03 17:35 UTC, fakenmc commented
Olá Pedro, solução aceite.

2019-12-03 17:35 UTC, merged