Adicionar a solução
VideojogosLusofona/lp2_exercicios pull request #69
Opened 2020-01-02 20:43 UTC by FPTheFluffyPawed

Olá professor, aqui mando a solução para o exercício, mas não tenho a certeza se fiz bem. Fiquei na dúvida sobre o que foi pedido para a classe, e não tenho a certeza se era preciso tornar `Partial` em `static` para poder ser acedido no código do `Program.cs`.

2020-01-03 10:49 UTC, fakenmc commented
Olá Inácio, este exercício foi colocado por engano, pois ainda não demos o _singleton pattern_, que será dado na próxima aula. Vou deixar o exercício em aberto, e depois da próxima aula propões uma solução corrigida-

2020-01-09 15:10 UTC, FPTheFluffyPawed commented
Professor, eu revi os _slides_ da aula e queria dizer que a minha solução parece que encaixa bem com o que foi dado. Será que pode rever a solução para aceitar?

2020-01-09 16:37 UTC, nunofachada requested changes
Inácio, por favor coloca as classes completas para ser mais fácil eu testar. Obrigado.

2020-01-09 21:37 UTC, nunofachada requested changes
* Classe `AddManager`
  * O construtor deve ser privado, caso contrário nada te garante que só tens uma instância. Uma vez que não especificaste um construtor, o mesmo é vazio (não tem problema) e público (tem problema).
  * O método `AddToTotal()` deve aceitar um inteiro, não um `object`.
* Classe `Adder`:
  * Deves lançar uma _thread_ que faz 1000 somas aleatórias entre 0 e 100. O que tu estás a fazer é a lançar 1000 _threads_, cada uma fazendo uma soma aleatória entre 0 e 100.
  * A instância da _thread_ não deve ser pública. Aliás, nem sequer precisas de uma variável de instância onde guardar a _thread_.
  * A propriedade `Partial` deve ser específica a cada instância de `Adder`. Não é o caso, pois está a ser partilhada entre todas as instâncias de `Adder`.
* Classe `Program`:
  * Se `AddManager` é um _singleton_ nunca poderias instanciá-la com o construtor, como estás a fazer.
  * As variáveis devem ser declaradas no início de cada bloco, embora possam ser inicializadas depois. A lista de _threads_ está a ser declarada após usares um `for`, o que é má prática.
  * Estás a obter incorretamente a _thread_ de cada `Adder`. Repara que nem fazes uso da lista de _threads_...
  * Não estás a somar `Partial` de todas as instâncias de `Adder` (aliás, como já referi acima, o teu `Adder` nem sequer tem um `Partial` por instância).
  * É suposto as somas serem iguais. Tenho dúvidas que neste programa as somas sejam iguais, pois várias _threads_ estão a aceder à variável partilhada `Partial` sem qualquer _lock_. Como já referi, `Partial` não deve ser partilhado, deve ser único por instância de `Adder`.

2020-01-11 16:03 UTC, FPTheFluffyPawed commented
Estou a tratar da solução e tenho uma dúvida. Se só suposto lançar a _thread_ que faz a soma 1000 vezes, donde é suposto fazer o `Thread.Start()`? Tenho agora o _script_ desta forma:

```cs
public class Adder
{
    public int Partial { get; set; }

    public Thread LetsAdd()
    {
        Random rnd = new Random();
        Thread t = new Thread(AddManager.SingleInstance.AddToTotal);

        for (int index = 0; index < 1000; index++)
        {
            int valueToAdd = rnd.Next(0, 101);
            // t.Start(valueToadd) aqui dá erro...
            Partial += valueToAdd;
        }

        return t;
    }
}
```

Se metesse o `Thread.Start()` fora do `for`, como iria passar o `valueToAdd` ao `Thread.Start()`?

2020-01-11 18:05 UTC, FPTheFluffyPawed commented
Envie o meu _commit_, mas estou com dúvida se fiz bem a forma de fazer a soma. Eu só lanço o _thread_ depois de fazer a soma. Eu não estou a ver como lançar o _thread_ antes de fazer a soma, a não ser que preciso de criar outro método específico para o `for`.

2020-01-12 16:03 UTC, nunofachada requested changes
Continua incorreto. Tens de olhar para os exercícios que resolvemos com _threads_. O método que passas à _thread_ para a _thread_ executar é normalmente um método à parte da mesma classe... e é nesse método à parte (que corre dentro da _thread_) que o método `AddToTotal()` de `AddManager` é executado 1000 vezes. O método `LetsAdd()` apenas cria e lança a _thread_, retornando a referência à _thread_ criada e lançada. Lê novamente as sugestões que fiz, tendo agora isso em conta.

2020-01-12 21:19 UTC, FPTheFluffyPawed commented
Ah, okay. Eu pensava que não podia meter um novo método para a parte de inserir valores _random_... Acho que agora ficou bem!

2020-01-12 21:42 UTC, merged

2020-01-12 21:43 UTC, fakenmc commented
Solução aceite.