Solução ao exercício 02_56
VideojogosLusofona/lp2_exercicios pull request #76
Opened 2020-01-04 22:02 UTC by FPTheFluffyPawed

2020-01-04 22:58 UTC, nunofachada requested changes
* O método `AnnotationToString()` pode simplesmente ser o _override_ do `ToString()`, que usamos normalmente. Assim o nome do método fica mais em linha com os restantes.
* Sobre as vantagens e desvantagens, os slides falam um pouco disso, em caso de dúvidas vê no livro da disciplina (C# Players Guide).

2020-01-04 23:14 UTC, FPTheFluffyPawed commented
No caso de chamar a função `ToString()`, posso então comentar o código incluído no enunciado o _override_ método `ToString()`? Como vi que a classe já têm o método, pensei que não podia chamar o método `ToString()` e que não podia remover o *override* existente.

2020-01-04 23:17 UTC, fakenmc commented
> No caso de chamar a função `ToString()`, posso então comentar o código incluído no enunciado o _override_ método `ToString()`? Como vi que a classe já têm o método, pensei que não podia chamar o método `ToString()` e que não podia remover o _override_ existente.

Ah, bem visto de novo. Deixa estar então como está.

2020-01-09 21:46 UTC, nunofachada requested changes
Relativamente à justificação final:

* Dá uma vista de olhos no Português, tens alguns (pequenos) erros (métodos em _chamas_?).
* Esta abordagem cria instâncias, ao contrário do que referes. Não vês lá o `new`? O mesmo acontece com as conversões definidas pelo utilizador.

2020-01-12 16:05 UTC, merged

2020-01-12 16:05 UTC, fakenmc commented
Solução aceite.