Solução 02_62
VideojogosLusofona/lp2_exercicios pull request #77
Opened 2020-01-17 21:08 UTC by FPTheFluffyPawed

2020-01-17 22:34 UTC, nunofachada requested changes
Olá Inácio, tens de pensar um pouco melhor na 2ª desvantagem, não está inteiramente correto da forma que explicas. A vantagem também não é muito clara, reformula por favor.

2020-01-18 14:09 UTC, nunofachada requested changes
Olá Inácio, ambos os pontos continuam confusos e mal explicados. Pesquisa um pouco sobre esses dois pontos antes de tentares melhorar a resposta.

2020-01-20 18:19 UTC, FPTheFluffyPawed commented
Mandei a minha alteração, penso que ficou bem. Uma pergunta, vale a pena eu acabar os outros dois _pull requests_, mesmo que já foi feito na aula?

2020-01-20 18:21 UTC, fakenmc commented
A poupança de memória não é a principal vantagem do _singleton_.
Podes terminar os outros _pull requests_, se quiseres.

2020-01-20 18:54 UTC, fakenmc commented
Ainda não é desta.

2020-01-20 19:07 UTC, FPTheFluffyPawed commented
A principal vantagem que posso pensar neste momento do _singleton_, é que os _singleton_ implementam interfaces e serem estendidos, enquanto as classes _static_ não podem... Também há aquilo que _singletons_ preventem outros objetos de criarem as suas próprias copias do _singleton_, certificando que só existe um _singleton_. Qual seria o mais apropriado para uma principal vantagem, estou mais inclinado ao primeiro facto...

2020-01-20 19:25 UTC, fakenmc commented
Tanto uma como outra são vantagens importantes do _singleton_. Atenção que "preventem" não existe em Português.

2020-01-20 19:38 UTC, merged

2020-01-20 19:38 UTC, fakenmc commented
Aceite.