Adicionar tentativa de solução
VideojogosLusofona/lp2_exercicios pull request #79
Opened 2020-01-18 14:48 UTC by FPTheFluffyPawed

2020-01-18 15:16 UTC, nunofachada requested changes
* E se eu quiser adicionar um NPC chamado "SimpleBeast" que tem apenas `Strength`?
* E se eu quiser adicionar um NPC chamado "DifferentBeast" que não tem nenhuma das características comuns a `Human` e `Orc`, tendo outras características diferentes, de número indeterminado?
* Vais ter que fazer o quê ao teu código para acomodar essas futuras alterações?
* Achas que o teu código está a respeitar o _Open-close principle_?
* Será mesmo necessário usar herança? Alguma coisa no enunciado te obriga a usar herança?
* Dito tudo isto, até poderei aceitar esta solução, desde que expliques claramente que se trata de uma solução com estas limitações e sugiras uma solução alternativa.

2020-01-18 15:28 UTC, FPTheFluffyPawed commented
Com essas duas primeiras alterações em mente, o código vai ter que ser modificado em `INPCFactorys` no método `CreateNPC()` a incluir um _overload_ que aceita esses parâmetros, e depois fazer o mesmo _override_ em `ToString()`. Não, o código não respeita o _Open-close principle_, um problema comum em _Simple factory pattern_, teríamos que utilizar _Factory pattern_ se queríamos arranjar esta violação do princípio.

Pensei que herança era necessário, pois `Human` e `Orc` utilizam variáveis comuns (`Strength`, `Dexterity` e `Charisma`) só com uma variável extra de cada um ser adicionada (`Wisdom` e `Endurance`), então optei por utilizar herança em ordem de não estar a declarar as mesmas variáveis em `Human` e `Orc`.

Pelo que entendi do problema e a pergunta do professor agora, essas são as minhas opiniões do meu ponto de vista de programador.

2020-01-18 15:36 UTC, FPTheFluffyPawed commented
Esqueci-me de mencionar que também teríamos que alterar `NPCFactory` para incluir o novo caso para o tipo `DifferentBeast`.

2020-01-18 16:30 UTC, FPTheFluffyPawed commented
Professor, depois de rever o código com a sua pergunta sobre herança em mente, vi que, na verdade poderia ter `NPC` como uma *interface*, por isso alterei o código de forma que `NPC` seja uma *interface* chamada `INPC`, que pode ajudar a fazer sentido em utilizar herança para as duas classes concretas. Quer que faça commit destas alterações?

2020-01-18 16:34 UTC, fakenmc commented
Olá Inácio, o _simple factory_ não tem esse problema. O que tem esse problema é o teu código. E esse problema resolve-se... não usando herança. Precisas mesmo de herança para o que é pedido no enunciado? As diferenças entre `Orc` e `Human` são assim tantas que precises de classes diferentes?

* Pergunta: O que contém um `Orc`? 
  * Resposta: Um nome "Orc" e um conjunto de variáveis do tipo `int`, cada uma com o seu nome.
* Pergunta: O que contém um `Human`? 
  * Resposta: Um nome "Human" e um conjunto de variáveis do tipo `int`, cada uma com o seu nome.

Agora pensa de novo. É preciso herança?

2020-01-18 16:37 UTC, fakenmc commented
Repara que eu aceitaria a tua solução fazendo uso de herança, que é a primeira solução que muitos programadores se lembram. No entanto a herança vai limitar-nos no futuro se as diferentes classes não partilharem assim tanta coisa. Dai a frase: "Prefere composição sobre herança". No entanto neste caso nem precisas de composição, porque as classes apenas têm umas variáveis, nem sequer têm métodos (comportamentos). Se tivessem usavas o _strategy pattern_ para fazeres composição de comportamentos.

2020-01-18 16:38 UTC, FPTheFluffyPawed commented
Ah, okay! Pensava que era necessário ter duas classes concretas separadas, já que o enunciado diz "duas classes concretas de `NPC`*... Então nesse caso, basta só fazer todas as variáveis dentro de `NPC`?

2020-01-18 16:39 UTC, fakenmc commented
Olha pois diz... bem visto de novo. Faz o seguinte: deixa estar a tua solução e adiciona/aponta as limitações da mesma, necessárias para estar de acordo com o enunciado.

2020-01-18 16:42 UTC, FPTheFluffyPawed commented
Ok. Nesse caso, quer que faço o commit de forma que `NPC` seja uma interface, para que fique mais limpo ou deixo como está agora?

2020-01-18 16:49 UTC, fakenmc commented
Olá Inácio, podes incluir a interface, embora não me pareça muito importante neste caso, pois simplesmente adiciona mais um ficheiro à solução. Vais ter de ter uma classe `NPC` abstrata na mesma, que seria a única a implementar a interface. Por isso mais vale simplificar e deixar como está.

No entanto podes colocar as classes como públicas e as propriedades com `private set`.

2020-01-18 16:55 UTC, FPTheFluffyPawed commented
Não penso que preciso de ter a classe `NPC`, basta só renombrar `NPC` para `INPC` para tornar-lâ em uma *interface*. Aqui têm a minha proposta. Só duas classes para mostrar o que tenho em mente!

**INPC.cs** (antes era **NPC.cs**)

```cs
    interface INPC
    {
        int Strength { get; set; }
        int Dexterity { get; set; }
        int Charisma { get; set; }

        string ToString();
    }
```

**Orc.cs**

```cs
    class Orc : INPC
    {
        public int Wisdom { get; set; }
        public int Strength { get; set; }
        public int Dexterity { get; set; }
        public int Charisma { get; set; }
        public int Endurance { get; set; }

        public Orc(int a, int b, int c, int d)
        {
            Strength = a;
            Dexterity = b;
            Charisma = c;
            Endurance = d;
        }

        public override string ToString()
        {
            return new string($"NPC: {NPCType.Orc}" +
                $"\nStrength: {Strength}" +
                $"\nDexterity: {Dexterity}" +
                $"\nCharisma: {Charisma}" +
                $"\nEndurance: {Endurance}");
        }
    }
```

2020-01-18 16:57 UTC, fakenmc commented
O problema é que vais repetir as propriedades comum em `Human` e `Orc` em ambas as classes. Tendo a classe `NPC` essas propriedades seriam definidas apenas uma vez.

2020-01-18 16:59 UTC, FPTheFluffyPawed commented
Ah, okay. Vou fazer commit da solução com a nota de que foi falado aqui então!

2020-01-18 17:19 UTC, FPTheFluffyPawed commented
Okay, já tá! Penso que fiz bem a explicação da nota e tentei dar o exemplo.

2020-01-18 17:43 UTC, fakenmc commented
Inácio, três coisas:

* Revê com atenção o Português, tens lá vários erros e frases esquisitas.
* Atenção ao Markdown, tudo o que forem _keywords_ de código (classes, variáveis, etc) deve vir em formatação de código.
* Classes devem ser públicas.
* Propriedades devem ter `set` privado.

2020-01-18 18:22 UTC, FPTheFluffyPawed commented
Meti o `private set` no `NPC`, mas não é permitido. Espero que isso não faça mal.

2020-01-18 18:26 UTC, fakenmc commented
De facto não pode ser `private`, pois as subclasses têm de aceder. No entanto também não pode ser `public` (é como está agora), senão qualquer classe pode alterar essas propriedades. Então qual é a solução?

2020-01-18 18:30 UTC, FPTheFluffyPawed commented
`Protected`! Já mando o commit!

2020-01-19 12:06 UTC, nunofachada requested changes
Olá Inácio, as propriedades da classe `NPC` devem ser `public`. Apenas o `set` deve ser `protected`.
Além disso, tens de dar um jeito no texto inicial, o Português está meio manhoso e tem alguns erros.

2020-01-19 12:12 UTC, fakenmc commented
Outra coisa, o `default` do `switch` que estás a usar na _factory_ não está a ser bem usado. Deves verificar explicitamente se o NPC é um `Orc`, e usas o `default` para gerar uma excepção ou algo do género, dando indicação de que se trata de um tipo desconhecido.

2020-01-19 15:21 UTC, nunofachada requested changes
* O princípio chama-se _Open-close**d**_.
* ~nós vamos ser~ -> somos
* ~Tendo em conta de isto~ -> Tendo isto em conta
* ~uma classe que têm **nada** em comum~ -> uma classe que não tem **nada** em comum
  * O exemplo `DifferentBeast` deveria ser uma sub-lista do ponto anterior. Tal como este ponto é uma sub-lista do ponto anterior.
  * Os erros de Português são tantos neste sub-ponto do `DifferentBeast` que acho melhor escreveres a frase de novo...
* ~se já sabemos que~ -> se tivermos a certeza de que
* ~diferenças adicionais sendo próprias aquela classe~ -> mal escrito e difícil de entender, reescreve por favor.
* "teremos que encontrar outra solução que encaixe bem ao o que nós queremos." ->  Podias dar uma sugestão, e senão quiseres estar a escrever muito podes procurar um _pattern_ apropriado [num dos livros da cadeira](https://gameprogrammingpatterns.com/contents.html) e sugerir o seu uso (dica: é um _pattern_ comportamental que não demos nas aulas).

2020-01-20 16:14 UTC, nunofachada requested changes
* ~mas têm limitações~ ->  mas tem limitações
  * A palavra **têm** é para o plural e lê-se "_tein-ein_". O singular é **tem**, e lê-se "_tein_". Lembra-te disto.
* ~nós vamos ser~ -> seremos
* ~sem os três campos por omissão de `NPC`~ -> sem os três campos já existentes em `NPC`
* ~o oposto que nós queremos~ -> o oposto do que nós queremos
* ~sejá~ -> seja
* ~sendo próprias aquela classe~ -> sendo próprias em cada subclasse
* ~a *pattern* de comportamento chamada~ ->  o *pattern* de comportamento chamado

2020-01-20 17:07 UTC, merged

2020-01-20 17:08 UTC, fakenmc commented
Aceitei, mas depois vi outro erro, que já tinha mencionado. É **o** _patern_ e não **~a~** _pattern_.

2020-01-20 17:09 UTC, FPTheFluffyPawed commented
Ainda posso corrigir mesmo depois de ter feito merge?

2020-01-20 17:10 UTC, fakenmc commented
Sim, experimenta corrigir e fazer _push_.

2020-01-20 17:13 UTC, FPTheFluffyPawed commented
Parece que não me deixa fazer push... Faço outro _pull request_ ou não vale a pena?

2020-01-20 17:13 UTC, fakenmc commented
Não vale a pena, eu corrijo. Corrige os outros problemas em aberto.