Solução 02_ex67
VideojogosLusofona/lp2_exercicios pull request #81
Opened 2020-01-19 03:36 UTC by FPTheFluffyPawed

Professor, tenho dúvidas sobre este exercício.

* O enunciado diz que as váriaveis `texture` e `attribute` tinham que ter o seu valor por omissão. O `default` era correto, ou era simplesmente fazer um `new` vazio para os dois?

* O enunciado diz "Caso a _string_ contenha caracteres que não `X`, `Y`, `A` e `B`, os mesmos devem ser ignorados.", que fiquei com a dúvida se a minha solução esta correta. Agora, a minha solução encontra os caracteres equivalentes a esses, e adiciona ao `secretPassPhrase` os correspondentes, o resto sendo ignorado. Fiz bem?

2020-01-19 12:25 UTC, fakenmc commented
* O valor por omissão é o `default`. Seja como for, no caso das listas isso significaria `null`, por isso alterei ligeiramente o enunciado do exercício 67 para essa parte mais clara.
* A forma como converteste a _string_ está correta.
* O problema é que não vais conseguir instanciar `ScenarioObject`s daquela forma, pois não podes inicializar variáveis de instância usando sintaxe de inicialização de propriedades. Na realidade nem as próprias propriedades poderias inicializar, pois as mesmas não têm `get`, tornando o exercício impossível de resolver. Alterei ligeiramente o enunciado 65 de modo a que as propriedades tenham `private set`. A alternativa seria usar um construtor, mas eu quero que resolvas o problema sem construtor.

2020-01-19 15:01 UTC, FPTheFluffyPawed commented
Ok, então nesse caso, basta só atualizar o enunciado na minha solução?

2020-01-19 15:09 UTC, fakenmc commented
> Ok, então nesse caso, basta só atualizar o enunciado na minha solução?

Não. Tens de fazer alterações na solução também. Lê melhor o que eu escrevi.

2020-01-19 15:09 UTC, FPTheFluffyPawed commented
Oops, desculpa. Já vi o problema. Vou corrigir.

2020-01-19 15:17 UTC, FPTheFluffyPawed commented
Eu originalmente fiz com os `private set`, porque me parecia raro que o exercício tinha esta pergunta, mas o código não deixava...

2020-01-19 15:25 UTC, fakenmc commented
Ok, está melhor, mas o código não vai funcionar ainda. Repito o que eu escrevi em cima: **não podes inicializar variáveis de instância usando sintaxe de inicialização de propriedades**.
Além disso, `null` não é uma lista vazia. `null` é o valor por omissão do tipo `List` (e de qualquer tipo de referencia).

2020-01-19 22:15 UTC, FPTheFluffyPawed commented
Já entendi! Desculpa, o meu cérebro estava a dar grande branca.

2020-01-20 16:03 UTC, nunofachada requested changes
Quase, mas a instanciação da lista está incorreta. Podes corrigir este erros de antemão colocando o código no Visual Studio...

2020-01-20 16:57 UTC, FPTheFluffyPawed commented
Testei o código no VS, e não me parece estar a dar erros. Aqui têm o meu código.

https://i.imgur.com/8Ek2GOI.png

No debugger mostra que a lista está a ser instanciada vazia. Estou a fazer algo mal aqui?

2020-01-20 17:06 UTC, fakenmc commented
> Testei o código no VS, e não me parece estar a dar erros. Aqui têm o meu código.
> 
> https://i.imgur.com/8Ek2GOI.png
> 
> No debugger mostra que a lista está a ser instanciada vazia. Estou a fazer algo mal aqui?

Esse screenshot não mostra onde está o "erro", que é na inicialização da lista. Por acaso fui testar e funciona, mas não é muito comum usares sintaxe de inicialização de coleções quando não estás a inicializar nada (não indicas objectos dentro das _curly brackets_). Usa antes a sintaxe normal de instanciação de objetos com construtor vazio, pois é mais comum e menos confuso.

2020-01-20 17:32 UTC, FPTheFluffyPawed commented
Ah, okay. Já entendi.

2020-01-20 17:40 UTC, merged

2020-01-20 17:40 UTC, fakenmc commented
Solução aceite.