Proposta de solução para o exercício 01_01
VideojogosLusofona/lp2_exercicios pull request #84
Opened 2020-10-14 16:36 UTC by FRP7

Qualquer tipo de feedback é bem vindo.

Para conseguir realizar pesquisei por estes artigos:
https://blogs.msmvps.com/deborahk/linq-mean-median-and-mode/
https://www.tutorialspoint.com/chash-average-method
https://stackoverflow.com/questions/1297231/convert-string-to-int-in-one-line-of-code-using-linq

2020-10-14 19:46 UTC, fakenmc requested changes
Olá Francisco,

Algumas sugestões para melhorares esta solução:

* Todos os membros de uma classe devem ter a visibilidade claramente explícita. Neste caso nenhuma das variáveis nem dos métodos tem a visibilidade definida explicitamente.
* Os números devem ser passados como parâmetros na linha de comandos no momento da invocação do programa. Ou seja, não devem ser pedidos ao utilizador tal como estás a fazer neste momento.
* Porque razão só permites 3 números?
* No menu não devias dizer qualquer coisa quando o utilizador insere uma opção inválida?
* Porque razão usas `WriteLines` dentro dos métodos para cálculo estatístico? Não deverias separar aquilo que é cálculo daquilo que é apresentação dos resultados ao utilizador?
* Porque razão voltas a chamar o método `Options()` dentro dos métodos para cálculo estatístico? Isto está a funcionar de forma recursiva: `Main()` chamada `Options()` que chamada método matemático, que chama `Options()`, etc e por ai fora. Devido a isto o teu programa vai ter um _stack overflow_ se fizeres um número muito alto de operações. É um _bug_. Porque razão não chamas o menu dentro de um _loop_? Ainda relacionado com isto, porque razão é preciso chamares o `Environment.Exit(0)` para sair do programa? Porque razão não deixas o programa terminar naturalmente?
* Quando fores fazer os testes de LP2 vais lembrar-te de como utilizar a classe `Queryable`? A razão deste exercício é treinares o teu raciocínio, calculando as diferentes estatísticas à mão (como aliás, está feito para a moda, e parcialmente para a mediana). O uso de Linq parece-me um bocado batotice. Aliás, só deves usar Linq quando souberes muito bem fazer as coisas sem Linq.

Alguma dúvida, pergunta.
Bom trabalho!

2020-10-15 10:11 UTC, fakenmc commented
Francisco, ainda relativamente ao que eu disse, lê este artigo por favor: https://stackoverflow.blog/2020/10/05/play-the-long-game-when-learning-to-code/

2020-10-15 16:27 UTC, FRP7 commented
Olá, já fiz umas alterações de acordo com o seu feedback.

- coloquei a visibilidade dos membros da classe explícita.

- refiz pela minha cabeça e sem Linq todos os cálculos menos a moda (amanhã tentarei fazer a moda 😅)

- coloquei também mais comentários a explicar como fiz os cálculos.

- Removi os Options() a mais

Amanhã tentarei fazer a moda e seguir o resto do seu feedback. 
Qualquer tipo de feedback novo é bem vindo.

2020-10-15 22:28 UTC, fakenmc requested changes
Olá Francisco, algumas coisas ainda por resolver:

* Não ultrapasses as 80 colunas (aqueles comentários logo ao início podem estar em cima de cada variável e não a seguir às mesmas).
* As variáveis de classe devem ser instanciadas no `Main()` e não no sítio onde são declaradas.
* Porque razão instancias os teus _arrays_ com capacidade para três números e depois fazes _resize_ dos _arrays_? Porque razão não instancias os _arrays_ logo com o tamanho correto? Além de ser muito mais simples, é mais eficiente.
* Continuas a não usar os números obtidos através dos argumentos da linha de comandos. Os números devem ser dados quando corres o programa, ex. `dotnet run -- 3 5 -12 4 5 0 123`. Estes números são passados para a variável `args` do `Main()` e tens de processá-los a partir dai. Os números **não** são para pedir ao utilizador interativamente.
* Nos comentários não comeces com "aqui faço isto, aqui faço aquilo". Os comentários devem ser declarativos e impessoais, por exemplo onde escreves "aqui converto os inputs do user" deveria estar "Converter os inputs do utilizador para inteiros" ou "Método que converte os inputs do utilizador para inteiros".
* Porque razão o teu _loop_ principal só permite ao utilizador fazer 6 operações e depois termina? E se o utilizador quiser pedir a média 20 vezes, por exemplo?
* Porque razão precisas do método `Exit()`? O programa não pode simplesmente terminar quando sais do _loop_ principal?
* Não faria mais sentido os teus métodos estatísticos devolverem o resultado em vez de estarem a fazer `WriteLines()`? Num bom programa as responsabilidades estão bem separadas. Há métodos para fazer os cálculos, métodos onde são realizadas as operações de _input_/_output_, etc.
* É preciso estares sempre a fazer `Sort()` do _array_? Não basta fazê-lo uma vez?
* Se tiveres o _array_ ordenado, obter o máximo e o mínimo ocupa uma linha de código e não aquelas todas...

2020-10-17 19:32 UTC, FRP7 commented
Olá, segui o seu feedback, só não consegui ainda terminar (de momento) o método da moda, estou a ter dificuldades em resolver...
Qualquer tipo de feedback é bem vindo!

2020-10-17 19:59 UTC, fakenmc commented
Olá Francisco,

* Repara que apagaste as soluções anteriores. Uma forma de as recuperares é fazeres _rebase_ do teu ramo em cima do `origin:master` e corrigires os _merge conflicts_ de modo a manteres tudo: as soluções já existentes e a tua.
* Para que serve a variável `arraysize`? O tamanho do _array_ está sempre disponível na sua propriedade `Length`.
* Não basta teres um _array_ de inteiros, inicialmente desordenado, que depois ordenas? É preciso teres um desordenado e outro ordenado? Para que precisas dos dois?
* No `Main()` porque razão usas um `foreach` se precisas de um índice (no teu caso, a variável `count`)? Porque não usar um `for` normal? Além disso, o uso de `var` é expressamente proibido em LP1 e LP2.
* Sobre o teu menu: não faz ciclo usar um ciclo `for` quando não sabes à partida o número de iterações que o ciclo vai ter. Há ciclos melhores para isso.
* Porque razao os teus métodos estatísticos chamam `Result()` para mostrar o resultado no ecrã? Se eu quiser reutilizar estes teus métodos estatísticos no Unity, a tua estratégia já não iria funcionar. Ao colocares os `WriteLines()` no método `Result()`, e depois chamares o método `Result()` a partir dos métodos estatísticos, estás apenas a varrer o problema que referi ontem para debaixo do tapete, pois os métodos estatísticos continuam agarrados ao funcionamento em consola. E eu quero que o vosso código funcione o mais possível em consola e em Unity.
* Os comentários nas variáveis iniciais estão incorretos. Não estás a "guardar" nada. Para as variáveis podes simplesmente dizer o que elas representam. Por exemplo em vez de "guardar os valores do args", deves dizer "Valores dos args". Melhor ainda: "Valores dados pelo utilizador na linha de comandos convertidos para inteiros".
* Ainda sobre os comentários, começa os mesmos com maiúscula, pois é assim que se começam as frases. Deves ainda também colocar um espaço entre "//" e o comentário em si. Incorreto: "//ordenar...". Correto: "// Ordenar...".

2020-10-22 11:22 UTC, FRP7 commented
Olá professor, segui o seu feedback, qualquer tipo de feedback é bem vindo!
Ainda não consegui fazer o método da moda de cabeça, acho que vou fazer outros exercícios enquanto não tiver ideias novas de como resolver.

2020-10-24 22:45 UTC, fakenmc requested changes
Olá Francisco, está melhor, mas ainda são necessárias algumas melhorias:

* Parece-me bastante limitativo só poderes trabalhar com inteiros. Então a média entre 4 e 5 é 4?
* Para que serve a variável `count` no `Main()`? Não podes simplesmente usar a variável `i`?
* É mesmo preciso meteres `i=7` quando o utilizador quer sair? E não fazeres nada dentro desse `else if`?
* Os teus métodos estatísticos continuam a chamar o método `Result()`. É uma abordagem incorreta devido às razões que expliquei no _feedback_ anterior. Estes métodos estatísticos devem **devolver** o valor calculado, que deve ser impresso no método `Options()`. Deves evitar poluir o código com `WriteLines()` e concentrá-los todos num mesmo método (ou classe, em projetos maiores).
* Tendo em conta o ponto anterior, todas aquelas variáveis `private static int` no início podem ser eliminadas.
* Quanto à moda, o código está porreiro, tirando o facto de teres variáveis declaradas a meio do método. Todas as variáveis devem ser declaradas no início do bloco onde serão usadas (neste caso o método). Tirando isso, que deves corrigir, qual é a tua dúvida especificamente?

2020-10-28 13:54 UTC, FRP7 commented
Olá professor, segui o seu feedback, qualquer tipo de feedback é bem vindo!
Consegui finalmente acabar de fazer a moda de cabeça utilizando Dictionary.

2020-10-28 23:20 UTC, fakenmc commented
Olá Francisco, não sei o que aconteceu mas adicionaste uma data de alterações dos teus colegas. Quero apenas a tua.

2020-11-02 10:57 UTC, fakenmc commented
Francisco, este _pull request_ faz alterações a 9 ficheiros. Tiveste um problema qualquer com o Git. Vou fechar e se for preciso abre novo _pull request_ apenas com a tua versão deste problema.

2020-11-02 10:57 UTC, closed without merging