Add solution to exercise 01_15
VideojogosLusofona/lp2_exercicios pull request #95
Opened 2020-10-23 14:20 UTC by condmaker

Não tinha certeza se colocava a conversão para cada propriedade (como Minutes { get => Seconds / 60 }), então deixei normal.

2020-10-24 22:52 UTC, fakenmc requested changes
Olá Marco, alguns comentários:

* Como é que defines os valores nesta `struct`, uma vez que a mesma não tem construtor?
* Se a `struct` é suposto representar um intervalo de tempo, fará sentido poderes definir um valor para segundos e outro para semanas, por exemplo? Dá uma vista de olhos na 1ª aula, na parte sobre propriedades, no exemplo da classe `Time`...
* Fará sentido usar `ints` para representar estes valores, que podem ser fracionáveis? (infelizmente o exemplo que dei na aula também tem este "bug"...)
* Onde está o programa para testar diferentes instâncias desta `struct`?

2020-10-26 10:48 UTC, fakenmc requested changes
Olá Marco, a resposta está essencialmente correta, mas podes melhorar um pouco a formatação do _output_. Experimenta correr o código para perceberes o que quero dizer.

2020-10-26 20:38 UTC, condmaker commented
Peço desculpas pela formatação. Eu havia me apercebido do erro, mas acho que apenas mudei no programa de teste e não no exercício em si.

2020-10-27 08:51 UTC, merged

2020-10-27 08:51 UTC, fakenmc commented
Resposta aceite.