Add solution to exercise 01_19
VideojogosLusofona/lp2_exercicios pull request #96
Opened 2020-10-23 14:23 UTC by condmaker

2020-10-24 22:55 UTC, fakenmc requested changes
Olá Marco,

* A resposta 1 está correta mas podes reduzir o número de "claramentes".
* A resposta 2 está incorreta. Como fazes um `set` guardar um valor numa posição específica de um _array_?

2020-10-26 09:53 UTC, condmaker commented
Na resposta 2, percebo que não é possível utilizar num `set` o código que apenas muda o valor na posição específica se tal posição for nula (que faz com que minha resposta esteja errada, mas não sei se é apenas isto ou se isto está correto sequer, e logo estou a escrever isto). Mas penso que é possível utilizar o `set` no geral, pois fiz um programa de teste onde a propriedade conseguia alterar a variável de suporte:
 
```csharp
public class Numbs
    {
        public int[] myNumbers; 
        public int[] MyNumbers { get => myNumbers; set { myNumbers = value; } }
    }

class Program
    {
        static void Main()
        {
            Numbs numTest = new Numbs();

            numTest.MyNumbers = new int[3];

            numTest.MyNumbers[2] = 2;

            Console.WriteLine(numTest.MyNumbers[2]);

            numTest.MyNumbers[1] = 2;
            numTest.MyNumbers[2] = 4;

            Console.WriteLine(numTest.MyNumbers[1]);
            Console.WriteLine(numTest.MyNumbers[2]);
        }
    }
```

Não tenho a certeza absoluta do porquê deste código funcionar, mas penso que ele implicitamente no `set` e `get` apanha o `myNumbers[posição]`.

2020-10-26 10:56 UTC, fakenmc commented
Repara que ao alterares o valor de uma posição do _array_ não estás a usar o `set` mas sim o `get`. Este último devolve o _array_, e uma vez tendo o _array_ podes aceder aos seus elementos individuais. O problema desta abordagem é que estás a expor o _array_ ao código externo à classe, quebrando a encapsulação. Pior, podes apagar totalmente o _array_ que lá está e substituir por outro completamente diferente. Mais: se no futuro decidires que um _array_ não é a melhor opção, ficas com as opções limitadas, pois muito código externo pode já assumir que se trata de um _array_, obrigando-te a alterar imensas coisas. A partir destes comentários acho que já consegues responder à alínea 2.

2020-10-28 23:22 UTC, fakenmc requested changes
Marco, a resposta 2 continua incorreta.

2022-10-09 18:58 UTC, closed without merging